config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: "pages#index"
  get 'pages' => 'pages#index'

  resources :clients do
    member do
      resources :tasks do
        member do
          post 'match'
        end
      end
    end
  end
  resources :volunteers do
    member do
      get 'available'
      get 'unavailable'
    end
  end
  resources :texts do
    member do
      post 'volunteer'
    end
  end

  post 'snow' => 'texts#snow_text'
  get 'settings' => 'settings#index'
  get 'settings/emails/list' => 'settings#email', as: 'email_list_settings'
  get 'match/:id' => 'match_task_volunteers#match', as: 'match'
  post 'match_one_volunteer/:id/:volunteer' => 'tasks#match_one_volunteer', as: 'match_one_volunteer'
  resources :admins

  put 'client_called/:id' => 'tasks#client_called', as: 'client_called'

  put 'task_completed/:id' => 'tasks#task_completed', as: 'task_completed'

end

app/views/partials/_assigned_tasks.html.erb
<li class='task-box'>
  <span class='client-request'>
    <strong><%= task.volunteer %></strong> is performing a task for <strong><%= task.client.name %> <%= task.client.last_name %></strong> 
  </span>
  <strong><%= task.task_type %></strong>
  <em><%= task.description %></em>
  <%= link_to "View this task", task_path(task), class: 'match-btn' %>
  <%= render 'partials/status_bar', task: task %>
</li>   

app/views/partials/_completed_tasks.html.erb
<li class='task-box completed'>
  <span class='client-request'>
    <strong><%= task.volunteer %></strong> has completed a task for <strong><%= task.client.name %> <%= task.client.last_name %></strong> 
  </span>
  <strong><%= task.task_type %></strong>
  <em><%= task.description %></em>
  <%= link_to "View this task", task_path(task), class: 'match-btn' %>
  <%= render 'partials/status_bar', task: task %>
</li>

app/views/partials/_dashboard.html.erb
<%= render 'partials/text_all_volunteers' %>

<h2 class='center'>TASKS TO BE ASSIGNED</h2>
<ul>
  <% @tasks_to_be_assigned.each do |task| %>
    <%= render 'partials/tasks_to_be_assigned', task: task %>
  <% end %>
</ul>

<h2 class='center'>ASSIGNED TASKS</h2>
<ul>
  <% @assigned_tasks.each do |task| %>
    <%= render 'partials/assigned_tasks', task: task %>
  <% end %>
</ul>

<h2 class='center'>COMPLETED TASKS</h2>
<ul>
  <% @completed_tasks.each do |task| %>
    <%= render 'partials/completed_tasks', task: task %>
  <% end %>
</ul>

app/views/partials/_hidden_fields.html.erb
<input type="hidden" id="lat" value=<%= task.geocoder_lat(task.client.postcode) %>>
<input type="hidden" id="long" value=<%= task.geocoder_long(task.client.postcode) %>>
<% if match_one %>
<input type="hidden" id="v-lat-one" value=<%= task.geocoder_lat(match_one.post_code) %>>
<input type="hidden" id="v-long-one" value=<%= task.geocoder_long(match_one.post_code) %>>
<input type="hidden" id="v-name-one" value=<%= match_one.name %>>
<% end %>
<% if match_two %>
<input type="hidden" id="v-lat-two" value=<%= task.geocoder_lat(match_two.post_code) %>>
<input type="hidden" id="v-long-two" value=<%= task.geocoder_long(match_two.post_code) %>>
<input type="hidden" id="v-name-two" value=<%= match_two.name %>>
<% end %>
<% if match_three %>
<input type="hidden" id="v-lat-three" value=<%= task.geocoder_lat(match_three.post_code) %>>
<input type="hidden" id="v-long-three" value=<%= task.geocoder_long(match_three.post_code) %>>
<input type="hidden" id="v-name-three" value=<%= match_three.name %>>
<% end %>

app/views/partials/_nav.html.erb
<nav class='menu_bar'>
  <ul class='navbar'>
    <li class='nav-link'><%= link_to "Add client", new_client_path %></li>
    <li class='nav-link'><%= link_to "View clients", clients_path %></li>
    <li class='nav-link'><%= link_to "Add volunteer", new_volunteer_path %></li>
    <li class='nav-link'><%= link_to "View volunteers", volunteers_path %></li>
    <li class='nav-link'><%= link_to "Volunteer availability", texts_path %></li>
    <li class='nav-link'><%= link_to "Settings", settings_path %></li>
  </ul>
</nav>

app/views/partials/_show_task.html.erb
<section class='task-box full-width'>
  <p class='client-request'><strong><span id='client-name'><%= task.client.name %> <%= task.client.last_name %></span></strong> has requested <strong><%= task.task_type %></strong></p>
  <p>Description: <%= task.description %></p>
  <p><strong>Phone: </strong><%= task.client.phone %></p>
  <p><strong>Address: </strong><%= task.client.address %></p>
  <p><strong>Postcode: </strong><%= task.client.postcode %></p>
</section>

app/views/partials/_show_volunteer.html.erb
<%if volunteer %>
<li class='task-box full-width'>
  <section class='vol-left'>
    <span class='client-request'><strong><%= volunteer.name %> <%= volunteer.last_name %></strong></span>
    <p><strong>Phone: </strong> <%= volunteer.mobile_number %></p>
    <p><strong>Address: </strong> <%= volunteer.address %></p>
    <p><strong>Postcode: </strong> <%= volunteer.post_code %></p>
    <% if volunteer.dbs %>
      <span class='status true'>THIS VOLUNTEER IS DBS CHECKED</span>
    <% end %>
  </section>

  <section class='btns'>
    <%= button_to "Assign Volunteer", match_one_volunteer_path(@task, volunteer), class: 'red-btn', id: volunteer.last_name %>
    <%= form_tag volunteer_text_path(volunteer), :id => volunteer.name do %>
      <%= text_field_tag :custom_body %>
      <p><%= submit_tag "Send text", class: 'red-btn' %></p>
    <% end %>
  </section>
</li>
<% end %>

app/views/partials/_splash.html.erb
<section class='left-container-splash'>
  <h1>  Welcome to Horsell Snow Angels </h1>
  </br>

  <h4>
  <p>Horsell Snow Angels is a community volunteer scheme in the postcode area of GU21 4**, which offers assistance for local people on snowy and icy days.</p>

  <p>Our hotline number for assistance on snowy and icy days is 01483 380025.</p>

  <p>Snow Angels provides a non-emergency temporary service, springing into action only during the snowy or icy weather, for anyone in Horsell to call upon who finds it difficult or risky to get around outside in those difficult conditions.</p>

  <p>The services offered by the Snow Angels volunteers range from snow clearance to shopping and prescription collection to dog walking. Services normally stop at the front door, so unlike more regular community support services such as Horsell Care, the Angels won’t give lifts or go into people’s homes. The Angels always travel on foot around the village.</p>

  <p>All Snow Angels are contacted by text message on snowy days to discover their availability for that day. Those who are available and in the village may be contacted by the organisers and asked to carry out specific tasks for local people. There is no commitment involved in volunteering - you just need to add yourself to a list of willing volunteers. To sign up as an Angel, use this website.</p>
  </h4>
  </br>

<%= link_to "Register as a volunteer", new_volunteer_path, class: 'volunteer-self-register' %>
</section>

</section>

app/views/partials/_status_bar.html.erb
<section>
  <ul class='status-bar'>
    <%= status_progress(task.volunteer_id, 'VOLUNTEER ASSIGNED') %>
    <%= link_to client_called_path(task), method: :put do %>
      <%= status_progress(task.called_client, 'CLIENT CALLED') %>
    <% end %>
    <%= link_to task_completed_path(task), method: :put do %> 
      <%= status_progress(task.task_done, 'TASK COMPLETED') %>
    <% end %>
  </ul>
</section>

app/views/partials/_tasks_to_be_assigned.html.erb
<li class='task-box'>
  <span class='client-request'>
    <strong><%= task.client.name %> <%= task.client.last_name %></strong> has requested <strong><%= task.task_type %></strong> 
  </span>
  <section class='central-section'>
    <em><%= task.description %></em>
    <%= link_to "Assign a volunteer", task_path(task), class: 'match-btn' %>
  </section>
  <%= render 'partials/status_bar', task: task %>

</li>   

app/views/partials/_text_all_volunteers.html.erb
<section class="sms_all_volunteers">
  <%= form_tag snow_path do %>
    <%= text_field_tag :custom_body, params[:custom_body], placeholder: 'SMS to all volunteers' %>
    <%= submit_tag "Send text" %>
  <% end %>
  <p class='center'><em>Send a text to all of the volunteers</em></p>
</section>