config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: "pages#index"
  get 'pages' => 'pages#index'

  resources :clients do
    member do
      resources :tasks do
        member do
          post 'match'
        end
      end
    end
  end
  resources :volunteers do
    member do
      get 'available'
      get 'unavailable'
    end
  end
  resources :texts do
    member do
      post 'volunteer'
    end
  end

  post 'snow' => 'texts#snow_text'
  get 'settings' => 'settings#index'
  get 'settings/emails/list' => 'settings#email', as: 'email_list_settings'
  get 'match/:id' => 'match_task_volunteers#match', as: 'match'
  post 'match_one_volunteer/:id/:volunteer' => 'tasks#match_one_volunteer', as: 'match_one_volunteer'
  resources :admins

  put 'client_called/:id' => 'tasks#client_called', as: 'client_called'

  put 'task_completed/:id' => 'tasks#task_completed', as: 'task_completed'

end

app/models/client.rb
class Client < ActiveRecord::Base


  validates_presence_of :address
  validates_presence_of :name
  validates_presence_of :phone
  validates_presence_of :last_name
  validates_presence_of :postcode

  has_many :tasks
  has_many :volunteers, :through => :tasks

  scope :ordered_by_last_name, -> { order('last_name ASC') }

  def self.search(query)
    where('name like ?', "%#{query}%")
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :authenticate_admin!
  before_action only: [:edit, :update, :destroy] { @client = find_client(params) }

  def index
    if params[:search]
      @clients = Client.search(params[:search]).ordered_by_last_name
    else
      @clients = Client.all.ordered_by_last_name
    end
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path
      flash[:notice] = "Client successfully added"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to pages_path
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    flash[:notice] = 'Client deleted successfully'
    redirect_to pages_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :last_name, :address, :postcode, :phone)
  end

  def find_client(params)
    Client.find(params[:id])
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<section class="form">
  <%= form_for @client do |f| %>
    <p><%= f.text_field :name, placeholder: 'First name' %></p>
    <p><%= f.text_field :last_name, placeholder: 'Last name' %></p>
    <p><%= f.text_field :address, placeholder: 'Address' %></p>
    <p><%= f.text_field :postcode, placeholder: 'Postcode' %></p>
    <p><%= f.text_field :phone, placeholder: 'Phone' %></p>
    <%= f.submit %>
  <% end %>
</section>

app/views/clients/edit.html.erb
<h2 class="form-title">Edit client</h2>
<%= render "form" %>

app/views/clients/index.html.erb
<h1>Clients</h1>

<%= form_tag(clients_path, :method => 'get', id: 'search-form-view') do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Search clients' %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<% if @clients.any? %>
  <table>
    <tr class="table_heading">
      <th>Last name</th>
      <th>First name</th>
      <th>Address</th>
      <th>Postcode</th>
      <th>Phone</th>
      <th>Add task</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.last_name %></td>
      <td><%= client.name %></td>
      <td class="address"><%= client.address %></td>
      <td><%= client.postcode %></td>
      <td><%= client.phone %></td>
      <td class="icon" id="icon_add_task"><%= link_to image_tag('AddTask.png'), new_task_path(client), {id: 'icon_add_task'} %></td>
      <td class="icon"><%= link_to image_tag('Edit.png'), edit_client_path(client) %></td>
      <td class="icon"><%= link_to image_tag('Delete.png'), client_path(client), method: :delete %></td>
    </tr>
  <% end %>

  </table>

<% end %>

app/views/clients/new.html.erb
<% if @client.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved: </h2>
    <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_tag(clients_path, :method => 'get', id: 'search-form-client') do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Search clients' %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<h2 class="form-title">Add a client</h2>
<%= render "form" %>