config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: "pages#index"
  get 'pages' => 'pages#index'

  resources :clients do
    member do
      resources :tasks do
        member do
          post 'match'
        end
      end
    end
  end
  resources :volunteers do
    member do
      get 'available'
      get 'unavailable'
    end
  end
  resources :texts do
    member do
      post 'volunteer'
    end
  end

  post 'snow' => 'texts#snow_text'
  get 'settings' => 'settings#index'
  get 'settings/emails/list' => 'settings#email', as: 'email_list_settings'
  get 'match/:id' => 'match_task_volunteers#match', as: 'match'
  post 'match_one_volunteer/:id/:volunteer' => 'tasks#match_one_volunteer', as: 'match_one_volunteer'
  resources :admins

  put 'client_called/:id' => 'tasks#client_called', as: 'client_called'

  put 'task_completed/:id' => 'tasks#task_completed', as: 'task_completed'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_action :authenticate_admin!
  def index 
  end

  def email
    @emails = Volunteer.pluck(:email)
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/email.html.erb
<h2>Emails</h2>
<% if @emails.any? %>
<pre>
  <% @emails.each do |email_address| %>
    <%= email_address %>
  <% end %>
</pre>
<% end %>

app/views/settings/index.html.erb
<h1> Settings </h1>

<h3>Email</h3>
<%= link_to 'Generate email list', email_list_settings_path, class: 'btn' %> -
<em>Generate a list of emails for your volunteers</em>
<br>

<h3>Manage Admins</h3>
<%= link_to "View Admins", admins_path, class: 'btn' %> -
<em>View and update authorised admins</em>

<h3>Admin Invitation</h3>
<%= link_to 'Admin Invitation', new_admin_invitation_path, class: 'btn' %> -
<em>Invite a new admin to the system</em>

<h3>Edit Profile</h3>
<%= link_to "Edit admin", edit_admin_registration_path %>
<em>Edit your data</em>