config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: "pages#index"
  get 'pages' => 'pages#index'

  resources :clients do
    member do
      resources :tasks do
        member do
          post 'match'
        end
      end
    end
  end
  resources :volunteers do
    member do
      get 'available'
      get 'unavailable'
    end
  end
  resources :texts do
    member do
      post 'volunteer'
    end
  end

  post 'snow' => 'texts#snow_text'
  get 'settings' => 'settings#index'
  get 'settings/emails/list' => 'settings#email', as: 'email_list_settings'
  get 'match/:id' => 'match_task_volunteers#match', as: 'match'
  post 'match_one_volunteer/:id/:volunteer' => 'tasks#match_one_volunteer', as: 'match_one_volunteer'
  resources :admins

  put 'client_called/:id' => 'tasks#client_called', as: 'client_called'

  put 'task_completed/:id' => 'tasks#task_completed', as: 'task_completed'

end

app/views/layouts/_footer.html.erb
<footer class="site-footer">""
</footer>

app/views/layouts/_header.html.erb
<span id='snowflake'>
  <%= image_tag 'snowflake50.png' %>
</span>
<span id='logo'>
  <%= link_to "Horsell Snow Angels", pages_path %> </span>

<% if !admin_signed_in? %>
  <%= link_to "Sign in", new_admin_session_path, class: 'login_logout_btn' %>
<% else %>
  <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "login_logout_btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnowAngels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


</head>
<body>

  <header>
    <%= render 'layouts/header' %>
  </header>

  <% if admin_signed_in? %>
    <%= render 'partials/nav' %>
  <% end %>

  <section class='page-wrap container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </section>

</body>
</html>